### PR TITLE
All TPT & Battle Text blocks finished and reviewed.

### PR DESCRIPTION
**Pull request by epidgin**

### CODE REVIEW

**Comment by epidgin** [comment]
I did this incorrectly, I will submit another pull request in a few hours.

**Comment by epidgin** [comment]
Okay,. I can't fix what I thought I could so I am reopening this request. I accidentally deleted m12-strings-english - Copy.txt from my fork, but re-uploaded it from my cloned docs from J's master. Same doc with no changes. However, m12-strings-english.txt is updated to reflect the following:
Blocks 400-499 complete, block 33 edited and complete, blocks 1105 and 1124 complete. Also a few blocks between 1300-1350 edited for line length.

**Comment by jeffman** [comment]
Looks good -- almost ready to merge. In the text tool, could you please run Tools -> Resolve duplicate labels? It'll auto-fix a bunch of duplicate labels but there's still two left over (L5863 and L5843).

**Comment by epidgin** [comment]
I resolved the duplicate labels, but I was unable to find any error with L5863 or L5843. The code for both matches the Japanese version. I will revisit these Labels as I go through all the blocks to check for errors.

**Comment by epidgin** [comment]
just repeating the comment from my last commit:
Blocks that may need checking:
- [0314]  - Egg Lady in Burglin Park
- [1137]  - Dynamic pronoun for girl/boy vs sir/maam
- [1227]  - Code for Item name [90 FF AF][1A FF 02 00] present. Replaced with item name.
- [1270]  - Many labels are more than 3 lines.
- [7B FF] - All saturn text for length.

**Comment by epidgin** [comment]
Reviewed PSI help text. No changes made, looks ok. May want to test for line length.

**Comment by epidgin** [comment]
I'm keeping a list of any labels that I'll need specifically double checked for accuracy, just as an FYI.
When I'm finally through everything, I'll send you the list and update the collaboration spreadsheet.

**Comment by jeffman** [comment]
Looks good, just a couple small things:

- There are a few references missing the L: 2784, 2775
- L3569 has an invalid code

**Comment by epidgin** [comment]
I have made the suggested corrections, but I have a question:
On label L3569 the code does not appear to match the Japanese version perfectly (specifically in the second half of the label). Is this for translation purposes, or is this broken?

**Comment by jeffman** [comment]
I think that's fine. It looks like the Japanese version repeats the item name in the second sentence but the English one doesn't, it just says "it" instead.

**Comment by epidgin** [comment]
Ok, cool! Thanks for the quick response!

**Comment by John-Enigma** [comment]
To add what @Jeffman said about L3569, I've noticed that the (hex?) line was "0000" instead of "00 00", whereas the majority of lines that look like this are always separate.

**Comment by epidgin** [comment]
Correct. That appeared to be the issue and has been corrected. I'm not sure how I missed that when going through everything, but it was a good catch by @jeffman

**Comment by epidgin** [comment]
On my last commit, I skipped L1845, L1846, L1847, L1848, L1848, L3447. I couldn't determine the correct translation to enter.
If anybody knows which lines these are supposed to correspond to in the EB Script, please let me know.

**Comment by epidgin** [comment]
Definitely not giving up. With how much there is to do, I may take a day or two off here and there for my in sanity lol.

Had a lot of personal stuff last week, but I'm back on the translation wagon! :)

**Comment by epidgin** [comment]
@John-Enigma my computer broke down about a week and a half ago. I thought I'd be able to get a replacement quickly, but that won't be the case. Looks like it's going to be around June when I have a computer to keep working on this again.

I'm very sorry for the bad news. :(

**Comment by jeffman** [comment]
It all compiles fine so I'm going to merge it in. Thanks again for the hard work!

**Comment by Karmageddon00** [comment]
Giegue199X said I should be in the contribution page.

**Pull request merged**
