### PR TITLE
TPT 0-300

### PR DESCRIPTION
**Pull request by PhoenixBound**
I finished looking over these changes today. These changes catch a few things that pidgin's fork didn't get to yet.

* Added a few more new labels: `pickypoint`, `hisher`, `kidkids`, `adultetc`. All the text that uses them is edited to use them in the translation too.
* Changed lots of whitespace to match the 144-pixel textbox this hack uses.
* Ported a bunch of references that got skipped somehow, including the Onett and Twoson newspapers.
* Fixed some typos, some of which existed in the EB text.
* Changed some dialogue that uses party leader in M12 to match EB text and display Ness's name every time. This could be edited back if that's a better idea though. (Looking now, I only see two examples, L4013 and L2443.)
* Added a version of @MalBound's hint newspaper "controller" and "TV" replacement text 'cause it was in these labels. (I said "game system" explicitly because the Japanese text doesn't even mention controllers, it just outright said whoever was playing the game.)

Besides the last two bullet points possibly needing edits, this is ready to merge.

### CODE REVIEW

**Comment by PhoenixBound** [comment]
I was looking over these labels and realized that the Stonehenge text I changed was broken in the original game. I'll work on a fix (and maybe squash all these commits so everything's a little less messy).

**Comment by jeffman** [comment]
I think the conflict is due to how the changes got applied in pidgin's fork. I'll see if I can resolve it.

**Comment by jeffman** [comment]
The conflicts are pretty complicated and I don't think I can fix it anytime soon :\ Do you think you could take a look at it?

**Comment by PhoenixBound** [comment]
Looks like all the line endings got changed around somewhere...I'll change my file to Unix style endings and see if it's easier to resolve.

**Comment by PhoenixBound** [comment]
It took some StackOverflow searching, but I think I got it to not completely break. I'll spend some time fixing the conflicts today and tomorrow.

**Comment by PhoenixBound** [comment]
Okay, ready for merge now.

**Pull request merged**
